// Top ~50 cities per state - compact static dataset for Brazil
export const ESTADOS = [
  {uf:"AC",nome:"Acre",cidades:["Rio Branco","Cruzeiro do Sul","Sena Madureira","Tarauacá","Feijó"]},
  {uf:"AL",nome:"Alagoas",cidades:["Maceió","Arapiraca","Palmeira dos Índios","Rio Largo","Penedo","União dos Palmares"]},
  {uf:"AM",nome:"Amazonas",cidades:["Manaus","Parintins","Itacoatiara","Manacapuru","Coari","Tefé"]},
  {uf:"AP",nome:"Amapá",cidades:["Macapá","Santana","Laranjal do Jari","Oiapoque","Mazagão"]},
  {uf:"BA",nome:"Bahia",cidades:["Salvador","Feira de Santana","Vitória da Conquista","Camaçari","Juazeiro","Itabuna","Ilhéus","Lauro de Freitas","Jequié","Teixeira de Freitas","Barreiras","Porto Seguro"]},
  {uf:"CE",nome:"Ceará",cidades:["Fortaleza","Caucaia","Juazeiro do Norte","Maracanaú","Sobral","Crato","Itapipoca","Maranguape","Iguatu","Quixadá"]},
  {uf:"DF",nome:"Distrito Federal",cidades:["Brasília","Ceilândia","Taguatinga","Samambaia","Planaltina","Gama","Sobradinho"]},
  {uf:"ES",nome:"Espírito Santo",cidades:["Vitória","Vila Velha","Serra","Cariacica","Cachoeiro de Itapemirim","Linhares","São Mateus","Colatina","Guarapari"]},
  {uf:"GO",nome:"Goiás",cidades:["Goiânia","Aparecida de Goiânia","Anápolis","Rio Verde","Luziânia","Águas Lindas de Goiás","Valparaíso de Goiás","Trindade","Formosa","Novo Gama","Catalão"]},
  {uf:"MA",nome:"Maranhão",cidades:["São Luís","Imperatriz","São José de Ribamar","Timon","Caxias","Codó","Paço do Lumiar","Açailândia","Bacabal","Balsas"]},
  {uf:"MG",nome:"Minas Gerais",cidades:["Belo Horizonte","Uberlândia","Contagem","Juiz de Fora","Betim","Montes Claros","Ribeirão das Neves","Uberaba","Governador Valadares","Ipatinga","Sete Lagoas","Divinópolis","Santa Luzia","Ibirité","Poços de Caldas","Patos de Minas","Varginha","Lagoa Santa","Itabira","Passos","Muriaé"]},
  {uf:"MS",nome:"Mato Grosso do Sul",cidades:["Campo Grande","Dourados","Três Lagoas","Corumbá","Grande Dourados","Ponta Porã","Naviraí","Nova Andradina","Aquidauana"]},
  {uf:"MT",nome:"Mato Grosso",cidades:["Cuiabá","Várzea Grande","Rondonópolis","Sinop","Tangará da Serra","Cáceres","Sorriso","Lucas do Rio Verde","Primavera do Leste"]},
  {uf:"PA",nome:"Pará",cidades:["Belém","Ananindeua","Santarém","Marabá","Castanhal","Parauapebas","Altamira","Abaetetuba","Bragança","Tucuruí","Marituba"]},
  {uf:"PB",nome:"Paraíba",cidades:["João Pessoa","Campina Grande","Santa Rita","Patos","Bayeux","Sousa","Cajazeiras","Cabedelo","Guarabira"]},
  {uf:"PE",nome:"Pernambuco",cidades:["Recife","Caruaru","Olinda","Petrolina","JABOATÃO DOS GUARARAPES","Paulista","Camaçari","Vitória de Santo Antão","Igarassu","Santa Cruz do Capibaribe","Belo Jardim"]},
  {uf:"PI",nome:"Piauí",cidades:["Teresina","Parnaíba","Picos","Piripiri","Floriano","Campo Maior"]},
  {uf:"PR",nome:"Paraná",cidades:["Curitiba","Londrina","Maringá","Ponta Grossa","Cascavel","São José dos Pinhais","Foz do Iguaçu","Colombo","Guarapuava","Paranaguá","Araucária","Toledo","Apucarana","Pinhais","Campo Largo","Almirante Tamandaré","Umuarama"]},
  {uf:"RJ",nome:"Rio de Janeiro",cidades:["Rio de Janeiro","São Gonçalo","Duque de Caxias","Nova Iguaçu","Niterói","Belford Roxo","São João de Meriti","Petrópolis","Volta Redonda","Magé","Itaboraí","Macaé","Campos dos Goytacazes","Nova Friburgo","Angra dos Reis","Resende"]},
  {uf:"RN",nome:"Rio Grande do Norte",cidades:["Natal","Mossoró","Parnamirim","São Gonçalo do Amarante","Macaíba","Ceará-Mirim","Caicó","Assu"]},
  {uf:"RO",nome:"Rondônia",cidades:["Porto Velho","Ji-Paraná","Ariquemes","Vilhena","Cacoal","Rolim de Moura","Guajará-Mirim"]},
  {uf:"RR",nome:"Roraima",cidades:["Boa Vista","Rorainópolis","Caracaraí","Alto Alegre","Mucajaí"]},
  {uf:"RS",nome:"Rio Grande do Sul",cidades:["Porto Alegre","Caxias do Sul","Canoas","Pelotas","Santa Maria","Gravataí","Viamão","Novo Hamburgo","São Leopoldo","Rio Grande","Alvorada","Passo Fundo","Sapucaia do Sul","Uruguaiana","Bagé","Santa Cruz do Sul","Cachoeirinha","Bento Gonçalves","Erechim","Montenegro","Lajeado"]},
  {uf:"SC",nome:"Santa Catarina",cidades:["Florianópolis","Joinville","Blumenau","São José","Chapecó","Criciúma","Itajaí","Jaraguá do Sul","Palhoça","Balneário Camboriú","Brusque","Tubarão","São Bento do Sul","Caçador","Lages","Concórdia","Camboriú","Navegantes"]},
  {uf:"SE",nome:"Sergipe",cidades:["Aracaju","Nossa Senhora do Socorro","Lagarto","Itabaiana","Caruaru","Estância","São Cristóvão"]},
  {uf:"SP",nome:"São Paulo",cidades:["São Paulo","Guarulhos","Campinas","São Bernardo do Campo","Santo André","Osasco","São José dos Campos","Ribeirão Preto","Sorocaba","Mauá","Mogi das Cruzes","Santos","Diadema","Jundiaí","Carapicuíba","Piracicaba","Bauru","São José do Rio Preto","Mogi Guaçu","Franca","Limeira","Araraquara","Taubaté","Praia Grande","Suzano","Taboão da Serra","Sumaré","Barueri","Cotia","Embu das Artes","Itapecerica da Serra","Americana","Marília","São Vicente","Jacareí"]},
  {uf:"TO",nome:"Tocantins",cidades:["Palmas","Araguaína","Gurupi","Porto Nacional","Paraíso do Tocantins","Colinas do Tocantins"]},
];
